### ISSUE TITLE
Does not cache finished commands if process fails on later step

### ISSUE THREAD

**Issue by ahwolf** [deanmalmgren/flo#32]
The caching functionality only works if all steps were completed successfully, if one step fails, then each step must be run again.

**Comment by deanmalmgren** [comment]
to reproduce, go into `examples/reuters-tfidf`, run `workflow` but kill after its done downloading the raw data but before it finishes. If you re-run `workflow`, it redownloads the data which is not terribly desireable

**Comment by deanmalmgren** [comment]
closed out by #20, which handles this issue in the same way.
