### ISSUE TITLE
`NOT FOUND` exception on subsequent runs

### ISSUE THREAD

**Issue by rarkins** [deanmalmgren/flo#72]
Output:

```
$ flo run
Traceback (most recent call last):
  File "/usr/local/bin/flo", line 14, in <module>
    run_subcommand(args)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/__init__.py", line 48, in run_subcommand
    command.execute(**args.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/run.py", line 58, in execute
    self.inner_execute(task_id, start_at, skip, only, force)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/run.py", line 48, in inner_execute
    self.task_graph.run_all_out_of_sync(mock_run=mock_run)
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 402, in run_all_out_of_sync
    self._run_helper(self.get_out_of_sync_tasks(), do_run_func, mock_run)
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 373, in _run_helper
    self.logger.info(self.duration_message(starting_tasks))
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 336, in duration_message
    for task in self.iter_tasks(tasks):
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 106, in iter_tasks
    raise Exception("NOT FOUND %s" % ([t.id for t in horizon], ))
Exception: NOT FOUND [u'massage/poi/output']
```

Flo seems to get itself "out of sync" somehow:
- The ones that are not found can change, but usually are ones near the bottom of my yaml file
- Removing `.flo` and running fresh works fine. It only errors on subsequent runs.

Further:

```
$ grep massage/poi/output .flo/*
grep: .flo/archive: Is a directory
.flo/duration.csv:massage/poi/output,14.938328981399536
.flo/state.csv:config:massage/poi/output,f9b89a4c69de3782a97dee9d31973b1654904e8d
.flo/state.csv:massage/poi/output,3f176f19882306396675a4c4a0c3c4d168cf8c46
```

**Comment by rarkins** [comment]
Also, I'm actively editing/enhancing my yaml file so that could be partly related.

**Comment by rarkins** [comment]
It just happened to me again. This time it was after I added a line to an existing "depends" list.
Removing the entry from duration did nothing.
Deleting all lines in `state.csv` that related to the task and its added dependent works around the problem. i.e. seems to be related to state.csv and dependencies. The tasks that get exceptioned are not necessarily the ones causing the problem.

**Comment by rarkins** [comment]
Here's another example:

I have a task defined like this:

``` yaml
---
creates: a/output
depends:
  - a/src
  - b/output
  - c/output
command: make a
```

Where all occurrences of `src` and `output` represent a directory.

Now I edit an SQL file inside `a/src` and get an error:

```
$ flo run
Traceback (most recent call last):
  File "/usr/local/bin/flo", line 14, in <module>
    run_subcommand(args)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/__init__.py", line 48, in run_subcommand
    command.execute(**args.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/run.py", line 58, in execute
    self.inner_execute(task_id, start_at, skip, only, force)
  File "/usr/local/lib/python2.7/dist-packages/flo/commands/run.py", line 48, in inner_execute
    self.task_graph.run_all_out_of_sync(mock_run=mock_run)
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 402, in run_all_out_of_sync
    self._run_helper(self.get_out_of_sync_tasks(), do_run_func, mock_run)
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 373, in _run_helper
    self.logger.info(self.duration_message(starting_tasks))
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 336, in duration_message
    for task in self.iter_tasks(tasks):
  File "/usr/local/lib/python2.7/dist-packages/flo/tasks/graph.py", line 106, in iter_tasks
    raise Exception("NOT FOUND %s" % ([t.id for t in horizon], ))
Exception: NOT FOUND [u'd/output', u'e/output']
```

Both d and e are tasks that depend on a.

Editing `.flo/state.csv` manually and removing the line starting with `a/output,` fixes it.

**Comment by rarkins** [comment]
It would seem that there's probably some logic error in [this code](https://github.com/deanmalmgren/flo/blob/master/flo/tasks/graph.py#L88-L103):

``` python
        source_tasks = tasks or self.get_source_tasks()
        distances = {}
        horizon = list(source_tasks)
        done, horizon_set = set(), set(source_tasks)
        source_tasks = set(source_tasks)
        while horizon:
            # before popping task off the horizon list, make sure all
            # of its dependencies have been completed
            found = False
            for task in horizon:
                if (
                    task in source_tasks or
                    not task.upstream_tasks.difference(done)
                ):
                    found = True
                    break
```

I can't get my head around what exactly it's doing yet, however I find it strange to see a `for task in horizon` inside a `while horizon` loop.

@deanmalmgren I don't suppose you'd help stamp out this bug? Unfortunately I hit it pretty much every time I change anything in a dependency directory.

**Comment by rarkins** [comment]
One final (I think) update for now: this problem only seemed to start once my `flo.yaml` got larger. i.e. I built up 10+ tasks and some dependencies initially with no problems. So I have a suspicion that it might have started once my dependency depth reached 2 (i.e. tasks relying on tasks relying on tasks).

**Comment by deanmalmgren** [comment]
@rarkins Sorry for the slow response. I've been onsite with a client the last two days and didn't get a chance to help out. If you have a chance to send along the output of `flo archive`, I can try and take a look at what's going on. 

Its hard for me to debug without a bit more information.

Thanks,
Dean

**Comment by rarkins** [comment]
Hi @deanmalmgren: never any need to apologise when supporting open source!

It looks like `flo archive` sucks up all the data with it? Actually the directory names are even sensitive, let alone the contents. I guess if my troubleshooting and code exploration so far is not enough then I'll need to find a way to reproduce it with a dummy data set.

**Comment by deanmalmgren** [comment]
Hmmm.. Yeah, it would be good if we can reproduce with a separate flo.yaml then. Maybe throw it in a gist or something?

**Comment by rarkins** [comment]
I'm not sure if/how I can do it, but will try to build it up sometime.
